#!/bin/bash

set -e

LINUX_DIR=$(realpath linux)
git clone --depth 1 --branch master git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git $LINUX_DIR

pushd $LINUX_DIR
make tinyconfig
./scripts/kconfig/merge_config.sh .config ../kernel.config

# Patch enables debug symbols in .init* sections of kernel modules
git apply ../kernel_scripts_gdb.patch

make bzImage -j4
make modules_prepare
make modules -j4
make modules_install INSTALL_MOD_PATH=out
popd

git clone --depth 1 --branch master git://busybox.net/busybox.git busybox
pushd busybox
make defconfig KBUILD_DEFCONFIG=../busybox.config 
make -j4
make install
popd

./mkinitrd

pushd usb-debug-whistle/subcomponents/kernel_module
make KERNEL_DIR=$LINUX_DIR USE_DKMS=n
popd

echo "Well done"
